### ISSUE TITLE
Images copied from *specificially* Google Images tab are blank.

### ISSUE THREAD

**Issue by Mr-Foxtrot** [Rainclip/Rainclip-Issues#25] opened 2024-02-08 09:54 UTC
Software is amazing, however it's frustrating trying to copy images from google in the Images tab as trying to do so will result in the copied image becoming blank with the default placeholder image. It can't be pasted anywhere and just takes up space in the history.

My only guess is it's either because I'm using Opera GX, or the format of jpg on the Google Images tab is different enough to make the software not read it properly. Also, after opening the "show clipboard" option in the settings, my computer slows to a crawl for a few seconds before speeding up. Then, temporarily copying from Google Images works again until a few minutes pass and it stops working.

Note: After digging into a debug log it says it's trying to read the image data that was copied from google images as a local URL, despite being in base64.

[Rainclip-debug-log.txt](https://github.com/Rainclip/Rainclip-Issues/files/14207316/Rainclip-debug-log.txt)

**Comment by Rainclip** [comment] 2024-02-09 12:35
The problem caused by data urls which Rainclip tried to use as the file name and that did not work. The issue has been now fixed in v1.9.118. I also improved the performance of the clipboard monitor when there is a large binary in the clipboard.

**Closed as completed by Rainclip** 2024-02-09 12:35 UTC
